# curl -F 'file=@testfile.txt' http://localhost:3000/upload
POST http://localhost:3000/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testfile.txt"

< testfile.txt
--WebAppBoundary--

###
